export const colors = {
  surface: '#f9f9ff',
  surfaceDim: '#d3daef',
  surfaceBright: '#f9f9ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f1f3ff',
  surfaceContainer: '#e9edff',
  surfaceContainerHigh: '#e1e8fd',
  surfaceContainerHighest: '#dce2f7',
  onSurface: '#141b2b',
  onSurfaceVariant: '#434655',
  background: '#f9f9ff',
  onBackground: '#141b2b',
  primary: '#004ac6',
  onPrimary: '#ffffff',
  primaryContainer: '#2563eb',
  onPrimaryContainer: '#eeefff',
  secondary: '#712ae2',
  onSecondary: '#ffffff',
  secondaryContainer: '#8a4cfc',
  accentCyan: '#38BDF8',
  positiveEmerald: '#16A34A',
  negativeRed: '#EF4444',
  error: '#ba1a1a',
  outline: '#737686',
  outlineVariant: '#c3c6d7',
} as const;

export type ColorName = keyof typeof colors;
